### ISSUE TITLE
Unrecognized field "cpuFrequency" 

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-utility-evaluator#12]
On PROD env, utility evaluator crashes with:
```
java.lang.IllegalArgumentException: Unrecognized field "cpuFrequency" (class org.ow2.proactive.sal.model.Hardware), not marked as ignorable (10 known properties: "state", "owner", "cores", "location", "id", "providerId", "disk", "ram", "fpga", "name"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.lang.Object[][0]->org.ow2.proactive.sal.model.NodeCandidate["hardware"]->org.ow2.proactive.sal.model.Hardware["cpuFrequency"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4618) ~[jackson-databind-2.16.1.jar!/:2.16.1]
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4549) ~[jackson-databind-2.16.1.jar!/:2.16.1]
        at eu.nebulous.utilityevaluator.communication.sal.NodeCandidatesFetchingService.getNodeCandidatesViaMiddleware(NodeCandidatesFetchingService.java:61) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.UtilityEvaluatorController.createInitialCostPerformanceIndicators(UtilityEvaluatorController.java:43) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler.onMessage(DslGenericMessageHandler.java:53) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler$onMessage.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Consumer.onDelivery(Consumer.groovy:77) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$4.run(Manager.groovy:174) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

**Comment by rudi** [comment]
Same error as https://github.com/eu-nebulous/optimiser-controller/issues/49
