### ISSUE TITLE
Optimiser utility evaluator crashes permanently if recieves an invalid app creation message

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-utility-evaluator#5]
For some unknown reason, an invalid app creation message was sent to the `eu.nebulouscloud.ui.dsl.generic` topic. This message caused utility evaluator to fail permanently, not reacting to further legit app creation messages.

The logs of the event:

```
Received by custom handler ui_generic_message => eu.nebulouscloud.ui.dsl.generic
2024-07-30T12:24:58.116Z  INFO 1 --- [pool-3-thread-2] e.n.u.c.e.DslGenericMessageHandler       : Body={when=2024-07-30T12:24:57.703192397Z}
2024-07-30T12:24:58.116Z ERROR 1 --- [pool-3-thread-2] e.n.utilityevaluator.model.Application   : Could not read app creation message

java.lang.IllegalArgumentException: argument "content" is null
        at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:5054) ~[jackson-databind-2.16.1.jar!/:2.16.1]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3276) ~[jackson-databind-2.16.1.jar!/:2.16.1]
        at eu.nebulous.utilityevaluator.external.KubevelaAnalyzer.parseKubevela(KubevelaAnalyzer.java:195) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.model.Application.<init>(Application.java:53) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler.onMessage(DslGenericMessageHandler.java:45) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler$onMessage.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$3$onMessage.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.core.Consumer.onDelivery(Consumer.groovy:77) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$4.run(Manager.groovy:174) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2024-07-30T12:24:58.120Z ERROR 1 --- [pool-3-thread-2] eu.nebulouscloud.exn.core.Manager        : General exception for topic://eu.nebulouscloud.ui.dsl.generic.>

java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "eu.nebulous.utilityevaluator.model.Application.getVariables()" is null
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler.onMessage(DslGenericMessageHandler.java:46) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler$onMessage.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$3$onMessage.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.core.Consumer.onDelivery(Consumer.groovy:77) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$4.run(Manager.groovy:174) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

**Comment by rudi** [comment]
optimiser-controller and utility-evaluator share code to parse app creation messages; please share the invalid app creation message if possible so this can be fixed and unit-tested.  The fix will apply to both libraries.

**Comment by robert-sanfeliu** [comment]
According to the logs posted above, the app creation message was "empty":

```
Received by custom handler ui_generic_message => eu.nebulouscloud.ui.dsl.generic
2024-07-30T12:24:58.116Z  INFO 1 --- [pool-3-thread-2] e.n.u.c.e.DslGenericMessageHandler       : Body={when=2024-07-30T12:24:57.703192397Z}
```

I can not provide you further info on that.

**Comment by rudi** [comment]
Thanks, that's enough info actually :)
