### ISSUE TITLE
Optimiser utility evaluator crashes permanently if exn-middleware fails with a 500 error

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-utility-evaluator#7]
When utility evaluator gets a 500 error code after sending a request to SAL (due to SAL being down), utility evaluator crashes permanently not being able to handle new requests even if SAL comes back online.

```
2024-09-19T12:21:11.748Z  INFO 1 --- [pool-3-thread-2] e.n.u.converter.VariableConverter        : Component: /spec/components/0
2024-09-19T12:21:11.748Z  INFO 1 --- [pool-3-thread-2] e.n.u.converter.VariableConverter        : meaning: replicas
2024-09-19T12:21:11.748Z  INFO 1 --- [pool-3-thread-2] e.n.u.converter.VariableConverter        : Adding new variable: spec_components_0_traits_0_properties_replicas for component: /spec/components/0
2024-09-19T12:21:11.748Z  INFO 1 --- [pool-3-thread-2] e.n.utilityevaluator.model.Application   : Application message successfully parsed
2024-09-19T12:21:11.748Z  INFO 1 --- [pool-3-thread-2] e.n.u.c.e.DslGenericMessageHandler       : Application 1421091909mercabarna-intralogistics1726748469297, with name eut-dummy-app-uc2, has variables: {/spec/components/0=[eu.nebulous.utilityevaluator.model.VariableDTO@44de64d5]}
2024-09-19T12:21:12.272Z  INFO 1 --- [pool-3-thread-2] e.n.u.c.s.NodeCandidatesFetchingService  : Received a response
2024-09-19T12:21:12.415Z ERROR 1 --- [pool-3-thread-2] e.n.u.c.s.NodeCandidatesFetchingService  : exn-middleware-sal request failed with error code '500' and message 'Generic exception while handling request for user Unparsable Generic Internal Error'
2024-09-19T12:21:12.415Z  INFO 1 --- [pool-3-thread-2] e.n.u.c.s.NodeCandidatesFetchingService  : Correctly return SAL response for component /spec/components/0, payload:
2024-09-19T12:21:13.156Z ERROR 1 --- [pool-3-thread-2] eu.nebulouscloud.exn.core.Manager        : General exception for topic://eu.nebulouscloud.ui.dsl.generic.>

java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Unknown Source) ~[na:na]
        at java.base/java.util.Arrays$ArrayList.<init>(Unknown Source) ~[na:na]
        at java.base/java.util.Arrays.asList(Unknown Source) ~[na:na]
        at eu.nebulous.utilityevaluator.communication.sal.NodeCandidatesFetchingService.getNodeCandidatesViaMiddleware(NodeCandidatesFetchingService.java:57) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.UtilityEvaluatorController.createInitialCostPerformanceIndicators(UtilityEvaluatorController.java:43) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler.onMessage(DslGenericMessageHandler.java:55) ~[classes!/:0.0.1-SNAPSHOT]
        at eu.nebulous.utilityevaluator.communication.exnconnector.DslGenericMessageHandler$onMessage.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$3$onMessage.call(Unknown Source) ~[na:na]
        at eu.nebulouscloud.exn.core.Consumer.onDelivery(Consumer.groovy:77) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73) ~[groovy-3.0.10.jar!/:3.0.10]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[groovy-3.0.10.jar!/:3.0.10]
        at eu.nebulouscloud.exn.core.Manager$4.run(Manager.groovy:174) ~[exn-connector-java-1.0-SNAPSHOT.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

**Comment by rudi** [comment]
@robert-sanfeliu thanks -- I'll take a look. Note that it's not my code though so I hope it won't take too much time :/
